version: '3.3'

services:
  db:
    container_name: db-temp
    image: mysql:8.0.29
    command: --max_allowed_packet=1073741824 --innodb-log-file-size=536870912
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: NFL
      MYSQL_USER: user
      MYSQL_PASSWORD: password
